# Generated by Django 2.1 on 2018-08-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180821_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Contact',
        ),
    ]
